[package]
name = "fz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nucleo = { git = "https://github.com/helix-editor/nucleo", rev = "89e32f915eadf7eaa5656f6fe3ccce00de7701b6" }
